"""add a name column to transaction table

Revision ID: 9552868adfa8
Revises: eddb8a5ca89e
Create Date: 2026-05-23 19:14:40.311398

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9552868adfa8"
down_revision: str | Sequence[str] | None = "eddb8a5ca89e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("name", sqlmodel.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "name")
    # ### end Alembic commands ###
