"""remove type from category

Revision ID: eddb8a5ca89e
Revises: c1e948010d8a
Create Date: 2026-05-23 18:51:31.206951

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eddb8a5ca89e'
down_revision: str | Sequence[str] | None = 'c1e948010d8a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('type', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
